import { NextRequest } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import { getUserFromRequest, errorResponse, successResponse } from '@/lib/auth'
import { execInContainer, ensureContainerRunning } from '@/lib/docker'

type Params = { params: Promise<{ id: string }> }

export async function GET(req: NextRequest, { params }: Params) {
  const user = getUserFromRequest(req)
  if (!user) return errorResponse('Unauthorized', 401)
  const { id } = await params
  await ensureContainerRunning(id)

  const { data: project } = await supabaseAdmin
    .from('projects')
    .select('container_id, user_github_id')
    .eq('id', id)
    .eq('user_github_id', user.id)
    .single()

  if (!project || !project.container_id) return errorResponse('Project container not found', 404)

  let pubKey = ''
  let hasKey = false
  let history = []

  try {
    const exitCode = await execInContainer(project.container_id, ['test', '-f', '/home/coder/.ssh/id_ed25519'], () => {})
    if (exitCode === 0) {
      hasKey = true
      await execInContainer(project.container_id, ['cat', '/home/coder/.ssh/id_ed25519.pub'], (data) => {
        pubKey += data
      })
      // Load history
      let historyData = ''
      const histExit = await execInContainer(project.container_id, ['cat', '/home/coder/.ssh/key_history.json'], (data) => { historyData += data })
      if (histExit === 0 && historyData) {
        try { history = JSON.parse(historyData) } catch (e) {}
      }
    }
  } catch (err) {
    hasKey = false
  }

  return successResponse({ hasKey, publicKey: hasKey ? pubKey.trim() : null, history })
}

export async function POST(req: NextRequest, { params }: Params) {
  const user = getUserFromRequest(req)
  if (!user) return errorResponse('Unauthorized', 401)
  const { id } = await params
  await ensureContainerRunning(id)

  const { data: project } = await supabaseAdmin
    .from('projects')
    .select('container_id, user_github_id')
    .eq('id', id)
    .eq('user_github_id', user.id)
    .single()

  if (!project || !project.container_id) return errorResponse('Project container not found', 404)

  try {
    await execInContainer(project.container_id, ['mkdir', '-p', '/home/coder/.ssh'], () => {})
    
    // Check if key already exists in the global volume (generated by another container)
    let hasKey = false
    // Ensure coder owns the volume before generating
    await execInContainer(project.container_id, ['chown', '-R', 'coder:coder', '/home/coder/.ssh'], () => {}, 'root')

    // Force remove existing keys to avoid overwrite prompts
    await execInContainer(project.container_id, ['rm', '-f', '/home/coder/.ssh/id_ed25519', '/home/coder/.ssh/id_ed25519.pub'], () => {})

    await execInContainer(
      project.container_id,
      ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/home/coder/.ssh/id_ed25519', '-q'],
      () => {}
    )

    let pubKey = ''
    await execInContainer(project.container_id, ['cat', '/home/coder/.ssh/id_ed25519.pub'], (data) => {
      pubKey += data
    })

    // Update history
    let history: any[] = []
    let historyData = ''
    const histExit = await execInContainer(project.container_id, ['cat', '/home/coder/.ssh/key_history.json'], (data) => { historyData += data })
    if (histExit === 0 && historyData) {
      try { history = JSON.parse(historyData) } catch (e) {}
    }
    history.unshift({ timestamp: new Date().toISOString(), publicKey: pubKey.trim() })
    
    // Save history using a shell command properly writing JSON string
    const escapedJson = JSON.stringify(history).replace(/'/g, "'\\''")
    await execInContainer(project.container_id, ['sh', '-c', `echo '${escapedJson}' > /home/coder/.ssh/key_history.json`], () => {})

    // Cache github keys to prevent interactive host verification dialog prompts
    await execInContainer(project.container_id, ['sh', '-c', 'ssh-keyscan github.com >> /home/coder/.ssh/known_hosts 2>/dev/null'], () => {})

    return successResponse({ hasKey: true, publicKey: pubKey.trim(), history })
  } catch (err) {
    return errorResponse(`Failed to generate SSH key: ${(err as Error).message}`, 500)
  }
}
